"""Add sold flag to containers

Revision ID: 2d1cf1e5a919
Revises: 4c6ae0af7cac
Create Date: 2025-02-01 15:45:57.373772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d1cf1e5a919'
down_revision = '4c6ae0af7cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold', sa.Boolean(), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=50),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('sold')

    # ### end Alembic commands ###
