"""Add image columns to container model

Revision ID: 31c849485b2e
Revises: 
Create Date: 2024-12-16 22:18:30.263918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31c849485b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image5', sa.String(length=200), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('image5')
        batch_op.drop_column('image4')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
